services:
  redis:
    image: "redis:alpine"
    ports:
      # Expose Redis to your local machine
      - "6379:6379"

  celery:
    build: .
    command: celery -A project worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      # These are now pointing to the redis service within the Docker network
      - DJANGO_SETTINGS_MODULE=project.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0