services:
  redis:
    image: redis:alpine
    ports:
      - "127.0.0.1:6379:6379"

  celery:
    build: .
    command: celery -A project worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
    # Add this environment section
    environment:
      - REDIS_HOST=redis